name: Update Config

on:
  schedule:
    - cron: "15,45 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 下载 Wiki
      - name: Download Wiki
        run: |
              curl -L \
              "https://raw.githubusercontent.com/wiki/Alvin9999-newpac/fanqiang/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7.md" \
              -o v2ray.md
          
              curl -L \
              "https://raw.githubusercontent.com/wiki/Alvin9999-newpac/fanqiang/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7.md" \
              -o ss.md
          
              cat v2ray.md ss.md > source.md

      # 提取完整 URI
      - name: Extract Nodes
        run: |
          grep -Eo \
          '(vmess|vless|trojan|ss|ssr|hysteria|hysteria2|tuic|anytls)://[^[:space:]<>"'\'']+' \
          source.md \
          | sort -u \
          > nodes.txt

          echo "节点数量："
          wc -l nodes.txt

  
      # 提交
      - name: Commit
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add source.md nodes.txt

          git commit \
            -m "Auto update nodes" \
            || echo "No changes"

          git push
